source 'https://rubygems.org'
ruby '~> 2.3.0'

gem 'jekyll', '>= 3.3.0'
gem 'jekyll-redirect-from', '>= 0.12.0'
gem 'jekyll-paginate'
gem 'crowdin-cli', '>= 0.5.5'
gem 'kramdown', '~>1.11' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge', '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'jekyll-assets', '~> 2.3', '>= 2.3.0'
gem 'sprockets-es6', '>= 0.9.1'
gem 's3_website'
gem 'octokit', '>= 4.6.0'
